language: cpp
dist: trusty
sudo: false
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
  matrix:
    - YARP_CHECKOUT=master
    - YARP_CHECKOUT=v2.3.72.1
    - YARP_CHECKOUT=v2.3.70.2

matrix:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=devel
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=devel

cache:
  directories: $CACHE_DIR

addons:
  apt:
    packages:
    - libboost-thread-dev # AMOR API
    - libeigen3-dev # AMOR API and YARP
    - libgtest-dev # unit testing
    - lcov # code coverage

before_install:
  #-- Configure Git (needed by YCM)
  - if [ ! `git config --get user.email` ]; then `git config --global user.email 'user@example.com'`; fi
  - if [ ! `git config --get user.name` ]; then `git config --global user.name 'Travis CI'`; fi

  #-- Register SSH deploy key for AMOR API private repository
  - source "$TRAVIS_BUILD_DIR/scripts/travis/configure-ssh.sh"

  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

install:
  #-- Install YCM
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YCM
    --repo-url https://github.com/robotology/ycm
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-${YCM_CHECKOUT:-master}}"

  #-- Install YARP
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install KDL
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name KDL
    --repo-url https://github.com/orocos/orocos_kinematics_dynamics
    --repo-checkout master
    --cmake-home-dir orocos_kdl
    --prepend-to-linker-path lib

  #-- Install color-debug
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name COLOR_DEBUG
    --repo-url https://github.com/roboticslab-uc3m/color-debug
    --repo-checkout master

  #-- (for AmorCartesianControl) Install AMOR API
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name AMOR_API
    --repo-url git@github.com:roboticslab-uc3m/amor-api
    --repo-checkout develop
    --additional-cmake-options "-DENABLE_udev_rules:BOOL=OFF"
    --prepend-to-linker-path lib

  #-- (for testBasicCartesianControl and apps using proximity sensors) Install yarp-devices
  - >
    "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name ROBOTICSLAB_YARP_DEVICES
    --repo-url https://github.com/roboticslab-uc3m/yarp-devices
    --repo-checkout develop
    --prepend-to-linker-path lib/yarp
    --additional-export-paths "YARP_DATA_DIRS;share/roboticslab-yarp-devices"

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install" -DENABLE_coverage:BOOL=ON
  - make install
  - export LD_LIBRARY_PATH=$PWD/install/lib:$PWD/install/lib/yarp:$LD_LIBRARY_PATH
  - export YARP_DATA_DIRS=$PWD/install/share/roboticslab-kinematics-dynamics:$YARP_DATA_DIRS

script:
  - bin/testKinRepresentation
  - bin/testKdlSolver
  - bin/testKdlSolverFromFile
  - bin/testAsibotSolverFromFile
  - bin/testKdlTrajectory
  - bin/testBasicCartesianControl

after_success:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then source "$TRAVIS_BUILD_DIR/scripts/travis/coverage.sh"; fi

  - make uninstall
