name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kinematics-dynamics
      uses: actions/checkout@v2

    - name: Checkout YCM
      uses: actions/checkout@v2
      with:
        repository: robotology/ycm
        path: .deps/ycm

    - name: Checkout YARP
      uses: actions/checkout@v2
      with:
        repository: robotology/yarp
        path: .deps/yarp

    - name: Checkout Orocos KDL
      uses: actions/checkout@v2
      with:
        repository: orocos/orocos_kinematics_dynamics
        path: .deps/kdl

    - name: Checkout color-debug
      uses: actions/checkout@v2
      with:
        repository: roboticslab-uc3m/color-debug
        path: .deps/color-debug

    - name: Install dependencies via apt
      run: sudo apt-get install -qq libeigen3-dev libgtest-dev

    - uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.12.x'

    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: kin-dyn-ccache-test

    - name: Create build trees
      run: cmake -E make_directory build .deps/ycm/build .deps/yarp/build .deps/kdl/orocos_kdl/build .deps/color-debug/build

    - name: Build YCM
      working-directory: ${{github.workspace}}/.deps/ycm/build
      run: |
        cmake ..
        cmake --build .
        sudo cmake --build . --target install

    - name: Build YARP
      working-directory: ${{github.workspace}}/.deps/yarp/build
      run: |
        cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DSKIP_ACE=ON -DYARP_DISABLE_VERSION_SOURCE=ON
        cmake --build . --parallel
        sudo cmake --build . --target install

    - name: Build Orocos KDL
      working-directory: ${{github.workspace}}/.deps/kdl/orocos_kdl/build
      run: |
        cmake .. -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build . --parallel
        sudo cmake --build . --target install

    - name: Build color-debug
      working-directory: ${{github.workspace}}/.deps/color-debug/build
      run: |
        cmake ..
        cmake --build .
        sudo cmake --build . --target install

    - name: Build and install kinematics-dynamics
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. -DENABLE_examples:BOOL=ON
        cmake --build .
        sudo cmake --build . --target install
        sudo ldconfig

    - name: Test kinematics-dynamics
      working-directory: ${{github.workspace}}/build/tests
      run: ctest -V

    - name: Uninstall kinematics-dynamics
      working-directory: ${{github.workspace}}/build
      run: sudo cmake --build . --target uninstall
