name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies via apt
      run: sudo apt-get install -qq libeigen3-dev libgtest-dev

    - name: Checkout YCM
      uses: actions/checkout@v2
      with:
        repository: robotology/ycm
        path: .deps/ycm

    - name: Build YCM
      run: |
        cmake -S .deps/ycm -B .deps/ycm/build
        cmake --build .deps/ycm/build
        sudo cmake --install .deps/ycm/build

    - name: Checkout YARP
      uses: actions/checkout@v2
      with:
        repository: robotology/yarp
        path: .deps/yarp

    - name: Build YARP
      run: |
        cmake -S .deps/yarp -B .deps/yarp/build -DSKIP_ACE:BOOL=ON
        cmake --build .deps/yarp/build --parallel
        sudo cmake --install .deps/yarp/build

    - name: Checkout Orocos KDL
      uses: actions/checkout@v2
      with:
        repository: orocos/orocos_kinematics_dynamics
        path: .deps/kdl

    - name: Build Orocos KDL
      run: |
        cmake -S .deps/kdl/orocos_kdl -B .deps/kdl/orocos_kdl/build
        cmake --build .deps/kdl/orocos_kdl/build --parallel
        sudo cmake --install .deps/kdl/orocos_kdl/build

    - name: Checkout color-debug
      uses: actions/checkout@v2
      with:
        repository: roboticslab-uc3m/color-debug
        path: .deps/color-debug

    - name: Build color-debug
      run: |
        cmake -S .deps/color-debug -B .deps/color-debug/build
        cmake --build .deps/color-debug/build
        sudo cmake --install .deps/color-debug/build

    - name: Configure kinematics-dynamics
      run: cmake -S . -B ./build -DENABLE_examples:BOOL=ON

    - name: Build and install kinematics-dynamics
      run: |
        cmake --build ./build
        sudo cmake --install ./build
        sudo ldconfig

    - name: Test kinematics-dynamics
      working-directory: build/tests
      run: ctest -V

    - name: Uninstall kinematics-dynamics
      run: sudo cmake --build ./build --target uninstall
